name: sshoot
version: git
summary: Manage sshuttle VPN sessions
description: |
  Command-line interface to manage multiple sshuttle VPN sessions.

  sshoot allows to define multiple VPN sessions using sshuttle and start/stop
  them as needed.

license: GPL-3.0+
confinement: classic
grade: stable
base: core24

environment:
  PYTHONPATH: "$SNAP/lib/python3.12/site-packages"

apps:
  sshoot:
    command: bin/sshoot
    completer: sshoot-completion

parts:
  sshoot:
    plugin: python
    source: .
    source-type: git
    stage-packages:
      - libpython3.12-minimal
      - libpython3.12-stdlib
      - python3.12-minimal
      - python3.12-venv
    python-packages:
      - .
      - sshuttle
    prime:
      - bin/python*
      - bin/register-python-argcomplete
      - bin/sshoot
      - bin/sshuttle
      - etc/
      - lib*/
      - pyvenv.cfg
      - usr/

  completion:
    plugin: dump
    source: snap/local
